name: NPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: npm ci --fund=false --audit=false
      - name: Run ESLint
        run: npm run eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: npm ci --fund=false --audit=false
      - name: Run Tests
        run: npm test
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#      - run: npm ci --fund=false --audit=false
#      - run: npm run build
#      - run: npm version prerelease --no-git-tag-version --preid ${{ github.ref_name }}-${{ github.sha }}
#      - uses: JS-DevTools/npm-publish@v3
#        with:
#          access: public
#          token: ${{ secrets.NPM_TOKEN }}
#          tag: beta
